### ISSUE TITLE
[Request] Update to Foundry V12

### ISSUE THREAD

**Issue by Hydrogen018** [AngryBeaver/bsa-pf2e#1]
Hello,

I was wondering if you had plans to update the PF2e implementations to Foundry V12. I loved using this module in previous versions of Foundry, and with a new campaign, I decided to upgrade to V12. Not knowing that while your core module is updated for V12, the PF2e module is incompatible. Currently, the PF2e implementation module can generate Recipe and AnyOf items, but they lack any of the formatting and recipe creation assets. Creating blank treasure items.  

If you don't have any plans or intentions to continue support for the PF2e implementation module. I would greatly appreciate some advice or guidance on how I could fork and update the module to V12 of Foundry to continue its support.

Thanks.

**Comment by AngryBeaver** [comment]
i am currently working on updateing all my bsa-x implementations due to a major release in beavers-crafting. 
I will look into the bsa-pf2e implementation soon. But the releases must be synchronized else it will break so i need to update all modules first. I assume it will be done in aproximatly a week.

**Comment by Hydrogen018** [comment]
Alrighty! That's great to hear. I appreciate the quick response and wish you the best of luck when it comes to updating. Hopefully, nothing too catastrophic happens in your endeavors and everything goes smoothly.

**Comment by AngryBeaver** [comment]
looking at v12 pf2e i do not encounter those issues:

![image](https://github.com/user-attachments/assets/6bd41b7d-3dbc-40f6-80e2-575a00f8b2b5)
while it is not yet pretty it is still functional.

plz hit f12 then open a recipe and look for any errors in the console.

**Comment by AngryBeaver** [comment]
nvm.. guess its already part of the major change: you probably will have something like this as an error:
![image](https://github.com/user-attachments/assets/042f76cc-c7df-4528-b32d-3fa3c170da9b)

**Comment by Hydrogen018** [comment]
You're correct, I get an identical error log.
![ErrorLog](https://github.com/user-attachments/assets/8e4167af-3a98-436e-a992-02aa1b8a6b89)

**Comment by AngryBeaver** [comment]
should now work with the latest beavers-crafting 4.0.0 and latest bsa-pf2e version.
